// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqhpRM1A5msUxo0G39vazYAoLs1tlOXew',
    appId: '1:763907694663:web:4ff6c6147a65540505d162',
    messagingSenderId: '763907694663',
    projectId: 'mybekkar-68202',
    authDomain: 'mybekkar-68202.firebaseapp.com',
    storageBucket: 'mybekkar-68202.firebasestorage.app',
    measurementId: 'G-2NZSYSRF33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGL44wTkefmAXqK2OFRM8RqwKe6iW6Ock',
    appId: '1:763907694663:android:95e08677d451e57d05d162',
    messagingSenderId: '763907694663',
    projectId: 'mybekkar-68202',
    storageBucket: 'mybekkar-68202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFjgmXe9UFSlJvBSVXP1R8ZdhMu_H1bQ',
    appId: '1:763907694663:ios:788655cb74f3e10405d162',
    messagingSenderId: '763907694663',
    projectId: 'mybekkar-68202',
    storageBucket: 'mybekkar-68202.firebasestorage.app',
    iosBundleId: 'com.example.mybekkar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLFjgmXe9UFSlJvBSVXP1R8ZdhMu_H1bQ',
    appId: '1:763907694663:ios:788655cb74f3e10405d162',
    messagingSenderId: '763907694663',
    projectId: 'mybekkar-68202',
    storageBucket: 'mybekkar-68202.firebasestorage.app',
    iosBundleId: 'com.example.mybekkar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqhpRM1A5msUxo0G39vazYAoLs1tlOXew',
    appId: '1:763907694663:web:a6b3bb7d0dee776805d162',
    messagingSenderId: '763907694663',
    projectId: 'mybekkar-68202',
    authDomain: 'mybekkar-68202.firebaseapp.com',
    storageBucket: 'mybekkar-68202.firebasestorage.app',
    measurementId: 'G-6BL32R5W84',
  );

}